### PR TITLE
Added remove method

### PR DESCRIPTION
**Pull request by notangelmario**
Hi, @xstevenyung! Your project is really cool! I need this method in my app and I also noticed this solves #1.

Btw, I upgraded some dependencies. I tested them don't worry.

### CODE REVIEW

**Comment by xstevenyung** [comment]
Hey @notangelmario 

Sorry for the delay, I was away on vacation.

Thanks so much for the PR, I love your changes. Could you add a test in `sitemap.test.ts` for the `remove` function and some documentation ?

If you don't have time, no worries. I would take care of it.

Cheers 🙏

**Comment by notangelmario** [comment]
of course, no problem!

**Comment by notangelmario** [comment]
added documentation and testing. i think it's ready to be merged.

**Comment by xstevenyung** [comment]
Thanks a lot 🙏

**Pull request merged**
